[package]
name = "flame_decoration_simulator"
version = "0.1.0"
authors = ["rivques <38469076+rivques@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
